- name: Check if Consul binaries exist
  stat:
    path: "{{ consul_install_path }}/{{ consul_version }}/"
  register: preexisting

- name: Install Consul binaries
  become: true
  when: preexisting.stat.exists != true
  block:
    - name: Download Consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch }}.zip"
        dest: /tmp/consul.zip
        mode: 0777

    - name: Prepare install path
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ consul_install_path }}/{{ consul_version }}"
        - /etc/consul

    - name: Unpack Consul
      when: (is_synology is not defined) or (not is_synology)
      unarchive:
        src: /tmp/consul.zip
        remote_src: true
        dest: "{{ consul_install_path }}/{{ consul_version }}"

    - name: Unpack Consul (Synology)
      when: (is_synology is defined) and (is_synology)
      command: "7z x /tmp/consul.zip -o{{ consul_install_path }}/{{ consul_version }}"

    - name: Symlink versioned binary
      file:
        src: "{{ consul_install_path }}/{{ consul_version }}/consul"
        dest: /usr/local/bin/consul
        owner: root
        group: root
        state: link

    - name: Clean up
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/consul.zip

- name: Configure Consul
  become: true
  block:
    - name: Install helper scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u=rwx,g=rx,o=rx
      with_items:
        - src: consul-wait-for-leader.sh
          dest: /usr/local/bin
        - src: consul-destroy-install.sh
          dest: /usr/local/bin

    - name: Install systemd service
      copy:
        src: consul.service
        dest: "/etc/systemd/system/consul.service"
        mode: 644
      notify:
        - Restart Consul

    - name: Configure Consul
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u=rw,g=r,o=r
      with_items:
        - src: consul.hcl.j2
          dest: /etc/consul/consul.hcl
      notify:
        - Restart Consul

    - name: Enable Consul
      service:
        name: consul
        enabled: true
        state: started

    - name: Prepare systemd-resolved path
      file:
        path: "/etc/systemd/resolved.conf.d"
        state: directory
        mode: 0755

    - name: Set up systemd-resolved
      copy:
        src: resolved.conf.d/consul.conf
        dest: "/etc/systemd/resolved.conf.d/consul.conf"
        mode: 644
      notify:
        - Restart Systemd-resolved

- pause:
    seconds: 3

- name: Join Consul cluster
  command: "/usr/local/bin/consul join {{ groups[consul_node_group] | random }}"
  run_once: true

- name: Wait for leader
  command: /usr/local/bin/consul-wait-for-leader.sh
  register: leader_status