- name: Check if Consul binaries exist
  stat:
    path: "{{ consul_install_path }}/{{ consul_version }}/"
  register: preexisting
  tags:
    - consul

- name: Install Consul binaries
  become: true
  when: preexisting.stat.exists != true
  block:
    - name: Download Consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch }}.zip"
        dest: /tmp/consul.zip
        mode: 0777
      tags:
        - consul
    - name: Prepare install path
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ consul_install_path }}/{{ consul_version }}"
        - /etc/consul
      tags:
        - consul
    - name: Unpack Consul
      command: "unzip /tmp/consul.zip -d {{ consul_install_path }}/{{ consul_version }}/"
      tags:
        - consul
    - name: Symlink versioned binary
      file:
        src: "{{ consul_install_path }}/{{ consul_version }}/consul"
        dest: /usr/local/bin/consul
        owner: root
        group: root
        state: link
      tags:
        - consul
    - name: Clean up
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/consul.zip
      tags:
        - consul

- name: Configure Consul
  become: true
  block:
    - name: Install helper scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u=rwx,g=rx,o=rx
      with_items:
        - src: consul-wait-for-leader.sh
          dest: /usr/local/bin
        - src: consul-destroy-install.sh
          dest: /usr/local/bin
      tags:
        - consul
    - name: Install systemd service
      copy:
        src: consul.service
        dest: "/etc/systemd/system/consul.service"
        mode: 644
      notify:
        - Restart Consul
      tags:
        - consul
    - name: Configure Consul
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: u=rw,g=r,o=r
      with_items:
        - src: consul.hcl.j2
          dest: /etc/consul/consul.hcl
      tags:
        - consul
    - name: Enable Consul
      service:
        name: consul
        enabled: true
        state: started
      tags:
        - consul

- pause:
    seconds: 3

- name: Join Consul cluster
  command: "/usr/local/bin/consul join {{ groups[consul_node_group] | random }}"
  run_once: true
  tags:
    - consul

- name: Wait for leader
  command: /usr/local/bin/consul-wait-for-leader.sh
  register: leader_status
  tags:
    - consul