---
nomad_version: "1.4.3"
nomad_arch_map:
  aarch64: "arm64"
  armv7l: "arm"
  x86_64: "amd64"
  i386: "386"
nomad_arch: "{{ nomad_arch_map[ansible_machine] }}"
nomad_install_path: /usr/local/nomad
nomad_usb_install_path: /usr/local/nomad_usb
nomad_usb_version: "0.4.0"
nomad_usb_arch_map:
  aarch64: "arm64"
  armv7l: "armv7"
  x86_64: "amd64"
  i386: "i386"
nomad_usb_arch: "{{ nomad_usb_arch_map[ansible_machine] }}"
nomad_dc: home0
nomad_is_server: no
nomad_leader_group: nomads
nomad_bootstrap_expect: "{{ groups[nomad_leader_group] | length }}"
nomad_retry_join: ' [{% for host in groups[nomad_leader_group] %}"{{ host }}"{% if not loop.last %}, {% endif %}{% endfor %}]'
nomad_token_path: cluster/{{ node_datacenter }}/{{ ansible_hostname }}/nomad-vault
nomad_vault_token: "{% if nomad_is_server %}{{ lookup('community.hashi_vault.vault_kv2_get', nomad_token_path, engine_mount_point='kv').secret.token }}{% endif %}"

nomad_volumes:
  backups: 
    path: "/mnt/backups"
  mosquitto: 
    path: "/mnt/cluster/mosquitto"
  zwavejs2mqtt:
    path: "/mnt/cluster/zwavejs2mqtt"
  homeassistant: 
    path: "/mnt/cluster/homeassistant"
  nodered: 
    host: tseng
    path: "/var/lib/volumes/node-red"
  influxdb: 
    host: tseng
    path: "/var/lib/volumes/influxdb"
  grafana:
    host: tseng
    path: "/var/lib/volumes/grafana"
  prometheus:
    host: tseng
    path: "/var/lib/volumes/prometheus"
  homedb:
    host: tseng
    path: "/var/lib/volumes/homedb"