# By default, we skip some tags to avoid messing with the existing consul/nomad clusters
# Whenever a new node is added that needs consul/nomad, we run 'script/refresh-cluster' to run those tags specifically
---
- name: Apply base role
  hosts: servers
  roles:
    - role: base
  tags:
    - bootstrap

- name: Apply tailnet role
  hosts: tailnet
  roles:
    - role: tailnet
  tags:
    - bootstrap
    - tailnet

- name: Apply consul role
  hosts: consuls
  roles:
    - role: consul
      consul_is_server: yes
      consul_node_group: "consuls"
      consul_dc: "{{ node_datacenter }}"
  tags:
    - consul

- name: Apply consul-agent role
  hosts: servers:!consuls
  roles:
    - role: consul
      consul_node_group: "consuls"
      consul_dc: "{{ node_datacenter }}"
  tags:
    - consul

- name: Apply vault role
  hosts: vaults
  roles:
    - role: vault
      vault_datacenter: home0
  tags:
    - vault

- name: Apply nomad role
  hosts: nomads
  roles:
    - role: nomad
      nomad_is_server: yes
      nomad_node_group: "nomads"
      nomad_dc: "{{ node_datacenter }}"
  tags:
    - nomad

- name: Apply nomad worker role
  hosts: workers
  roles:
    - role: nomad
      nomad_node_group: "nomads"
      nomad_dc: "{{ node_datacenter }}"
  tags:
    - nomad

- name: Apply synology roles
  hosts: synology
  roles:
    - role: base
    - role: consul
  tags:
    - synology