---
- name: Restart Node Exporter
  become: true
  service:
    name: node_exporter
    state: restarted
- name: Reload telegraf
  become: true
  service:
    name: telegraf
    state: reloaded
- name: Restart Networkd
  become: true
  service:
    name: systemd-networkd
    state: restarted
- name: Restart dnsmasq
  become: true
  service:
    name: dnsmasq
    state: restarted
- name: Restart Avahi
  become: true
  service:
    name: avahi-daemon
    state: restarted
- name: Update CA certs
  become: true
  command: update-ca-certificates