---
- name: Microk8s Setup
  hosts: pis
  tasks:
  - name: Install microk8s
    become: yes
    community.general.snap:
      name: microk8s
      classic: yes
      channel: "1.21"
  - name: Give ansible user access
    become: yes
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups:
      - microk8s
    register: add_to_group
  - name: Wait for microk8s to be ready
    shell: "microk8s status --wait-ready"
    args:
      executable: /bin/bash