---
- name: Restart Node Exporter
  become: true
  service:
    name: node_exporter
    state: restarted
- name: Reload telegraf
  become: true
  service:
    name: telegraf
    state: reloaded
- name: Restart dnsmasq
  become: true
  service:
    name: dnsmasq
    state: restarted
- name: Restart Avahi
  become: true
  service:
    name: avahi-daemon
    state: restarted