---
consul_version: "1.14.3"
consul_checksum: "sha256:e7b6846fb338c31e238f9b70cc42bd35f7de804cc31d2d91fe23cbe5de948aae"
consul_is_server: no
consul_install_path: /usr/local/consul
consul_arch_map:
  aarch64: "arm64"
  armv7l: "arm"
  x86_64: "amd64"
  i386: "386"
consul_arch: "{{ consul_arch_map[ansible_machine] }}"
consul_dc: "home0"
consul_bind: "{{ ansible_default_ipv4.address }}"
consul_client: "{{ ansible_default_ipv4.address }}"
consul_advertise: "{{ ansible_default_ipv4.address }}"
consul_node_group: "consul_servers"
consul_nodes: "{% for host in groups[consul_node_group] %}\"{{ host }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
consul_node_count: "{{ groups[consul_node_group] | length }}"
