#!/usr/bin/env bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

context="k3s-home"
kubectl="kubectl --context=$context"

dry_run=false
while [[ $# -gt 0 ]]; do
    key="$1"
    shift

    case "$key" in
        -n|--dry-run)
            dry_run=true
            ;;
    esac
done

set -euo pipefail

helmfile apply

find -s "$root/k8s" \( -name "*.yml" -or -name "*.yaml" \) -type f -print0 | while read -d $'\0' file; do
    if $dry_run; then
        echo "==> diffing $file ..."
        # '|| true' ==> ignore a non-zero exit code.
        $kubectl diff -f $file || true
    else
        echo "==> applying $file ..."
        $kubectl apply -f $file
    fi
done

echo "==> reloading prometheus config"
if ! $dry_run; then
    $kubectl --namespace monitoring exec -it deployment/prometheus-deployment -- kill -1 1
fi