#!/usr/bin/env bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

for file in $(find "$root/k8s" -name "*.yml"); do
    echo "Applying $file ..."
    kubectl apply -f $file
done