#!/usr/bin/env bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

helmfile apply

for file in "$(find "$root/k8s" \( -name "*.yml" -or -name "*.yaml" \) -type f)"; do
    echo "==> applying $file ..."
    kubectl apply -f $file
done