#!/usr/bin/env bash
# Copies cloud-init content to the attached volume
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

volume="/Volumes/system-boot"

while [[ $# -gt 0 ]]; do
    key="$1"
    shift

    case "$key" in
        -v|--volume)
            volume="$1"
            shift
            ;;
    esac
done

echo "Copying cloud init files from $root/cloud-init to $volume"
cp -R $root/cloud-init/* $volume

if [[ -f $volume/user-data ]]; then
    if ! grep "^fqdn:" $volume/user-data > /dev/null; then
        echo -n "Enter the simple hostname for this node (without domain): "
        read hostname
        fqdn="$hostname.local.analogrelay.net"
        echo "Ok, I'll set the fqdn of this node to: $fqdn"

        echo "fqdn: $fqdn" >> $volume/user-data
    fi
fi

sdvol=$(mount | grep $volume | awk '{print $1}')
echo "Unmounting SD card volume $sdvol"
diskutil unmount $sdvol