#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root

if [ "$HOME_NIX_SHELL" != "1" ]; then
    echo "This script must be run from within a nix-shell."
    echo "Run 'script/activate' to enter a nix-shell."
    exit 1
fi

echo -n "SMB Password: "
read -s password
echo

file_content=$(cat <<EOF
username=cluster
password=$password

EOF
)

ansible servers -b -m "ansible.builtin.copy" -a "mode=0640 owner=root group=root dest=/etc/smb-credentials.txt content='$file_content'"