#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root

if [ "$HOME_NIX_SHELL" != "1" ]; then
    echo "This script must be run from within a nix-shell."
    echo "Run 'script/activate' to enter a nix-shell."
    exit 1
fi

ansible-playbook -i inventory.yaml --tags=consul --tags=nomad site.yaml