#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root

if [ "$HOME_NIX_SHELL" != "1" ]; then
    echo "This script must be run from within a nix-shell."
    echo "Run 'script/activate' to enter a nix-shell."
    exit 1
fi

if [ ! -f "$HOME/.vault-token" ]; then
    echo "You must be logged into vault to run this script."
    echo "Run 'script/vault-login' to log into vault."
    exit 1
fi

datacenter="home0"
while [[ $# -gt 1 ]]; do
    key="$1"
    shift
    case $key in
        -d|--datacenter)
            datacenter="$1"
            shift
            ;;
        *)
            echo "Unknown option: $key"
            exit 1
            ;;
    esac
done

# Read the node name from the terminal
echo -n "Node Name: "
read node_name

# Read the token from the terminal
echo -n "Tailscale Token: "
read -s token
echo

echo "Storing tailscale token for $node_name ..."
vault kv put -mount=kv cluster/$datacenter/$node_name/tailscale token=$token
