#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root

if [ "$HOME_NIX_SHELL" != "1" ]; then
    echo "This script must be run from within a nix-shell."
    echo "Run 'script/activate' to enter a nix-shell."
    exit 1
fi

if [ ! -f "$HOME/.vault-token" ]; then
    echo "You must be logged into vault to run this script."
    echo "Run 'script/vault-login' to log into vault."
    exit 1
fi

datacenter="home0"
node_name=
secret_name=
while [[ $# -gt 0 ]]; do
    key="$1"
    shift
    case $key in
        -d|--datacenter)
            datacenter="$1"
            shift
            ;;
        *)
            if [ -z "$node_name" ]; then
                node_name="$key"
            elif [ -z "$secret_name" ]; then
                secret_name="$key"
            else
                echo "Unknown option: $key"
                exit 1
            fi
            ;;
    esac
done

if [ -z "$node_name" ]; then
    echo "Usage: script/set-node-token [-d|--datacenter <datacenter>] <node-name> <secret-name>"
    exit 1
fi

if [ -z "$secret_name" ]; then
    echo "Usage: script/set-node-token [-d|--datacenter <datacenter>] <node-name> <secret-name>"
    exit 1
fi

# Read the token from the terminal
echo -n "Token: "
read -s token
echo

echo "Storing $secret_name token for $node_name ..."
vault kv put -mount=kv cluster/$datacenter/$node_name/$secret_name token=$token
