#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
cd $root

if [ "$HOME_SHELL" != "1" ]; then
    echo "Ensure 'direnv' is configured and allowed for this directory!"
    exit 1
fi

username=ashley
while [[ $# -gt 1 ]]; do
    key="$1"
    shift
    case $key in
        -u|--username)
            username="$1"
            shift
            ;;
        *)
            echo "Unknown option: $key"
            exit 1
            ;;
    esac
done

echo "Authenticating as $username ..."
if ! vault login -method=userpass username=$username >/dev/null; then
    echo "Failed to authenticate as $username."
    exit 1
fi