---
- name: Microk8s Setup
  hosts: k8s
  tasks:
  - name: Install microk8s
    become: yes
    community.general.snap:
      name: microk8s
      classic: yes
      channel: "1.21"
  - name: Give ansible user access
    become: yes
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups:
      - microk8s
    register: add_to_group
  - name: Update hostname
    become: yes
    lineinfile:
      path: /var/snap/microk8s/current/args/kubelet
      regexp: '^--hostname-override'
      line: "--hostname-override=${HOSTNAME}.local.analogrelay.net"
  - name: Wait for Microk8s to start
    shell: "microk8s status --wait-ready"
    args:
      executable: /bin/bash