- name: Configure APT Repos
  become: true
  block:
    - name: Fetch keys
      register: fetch_keys
      get_url:
        url: "{{ item.url }}"
        dest: "/etc/apt/trusted.gpg.d/{{ item.name }}.asc"
      with_items:
        - url: https://repos.influxdata.com/influxdb.key
          name: influxdb
    
    - name: Add repos
      register: add_repos
      apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.name }}"
        state: present
      with_items:
        - repo: "deb https://repos.influxdata.com/debian stable main"
          name: influxdb
    
    - name: Update cache
      when: fetch_keys.changed or add_repos.changed
      apt:
        update_cache: true

- name: Install packages
  become: true
  apt:
    pkg:
      - cifs-utils
      - dnsmasq
      - avahi-utils
      - telegraf
