- name: Configure Node Identity
  when: node_identified is defined and node_identified
  import_tasks: identity.yml

- name: Configure users
  when: (is_synology is not defined) or (not is_synology)
  import_tasks: users.yml

- name: Install packages
  when: (ansible_distribution_file_variety is defined) and (ansible_distribution_file_variety == "Debian")
  import_tasks: packages.debian.yml

- name: Configure telegraf
  when: node_monitored is defined and node_monitored
  import_tasks: telegraf.yml

- name: Configure node_exporter
  when: node_monitored is defined and node_monitored
  import_tasks: node_exporter.yml

- name: Place avahi config
  when: avahi_reflector is defined and avahi_reflector
  become: true
  copy:
    src: avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf
  notify: 
    - Restart Avahi

- name: Configure storage volumes
  when: node_storage is defined and node_storage
  import_tasks: volumes.yml