- name: Configure user/group
  become: true
  block:
  - name: Create groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
      - "admin"
      - "docker"

  - name: Create users
    user:
      name: "{{ item.name }}"
      comment: "{{ item.comment }}"
      groups: "{{ item.groups }}"
      append: true
      create_home: true
      shell: /bin/zsh
    with_items:
      - name: ashley
        comment: Ashley Stanton-Nurse
        groups: admin, docker

  - name: Configure SSH
    ansible.posix.authorized_key:
      key: "{{ item.key }}"
      user: "{{ item.user }}"
    with_items:
      - user: ashley
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjy0nnqPOijeAW1jA4a3e++tiKU7fWaXOkayfMypKs3"

  - name: Configure nopasswd sudo
    copy:
      src: ashley.sudoer
      dest: "/etc/sudoers.d/99-ashley"
      mode: 644